### ISSUE TITLE
Support Firefox

### ISSUE THREAD

**Issue by the-snesler** [JackBlake-zkq/cse-plus#6]
This would be greatly appreciated :)
Because the extension is built using Plasmo, the build step already produces a Firefox build (or can be modified to produce one? I'm building an extension with Plasmo and have to use --target=firefox-mv2). All that remains is submitting it at https://addons.mozilla.org/en-US/developers/

If there are concerns over the use of UW's logo, you can use this generic W I designed for another project that never made it off the ground: [uwlogo](https://github.com/JackBlake-zkq/cse-plus/assets/78718829/221f1c17-f21d-48a5-b8dc-4865ff594a5c)

**Comment by JackBlake-zkq** [comment]
Good point, was going to push out a big update on this over the summer so will get that set up

**Comment by JackBlake-zkq** [comment]
@TetraTsunami this is available now! [firefox add-ons page](https://addons.mozilla.org/en-US/firefox/addon/uw-madison-cse-plus)

**Comment by JackBlake-zkq** [comment]
Update: they won't let me publicly list it because it's not usable by everyone: Now it is a release with the signed xpi file:
https://github.com/JackBlake-zkq/cse-plus/releases/tag/Firefox

**Comment by the-snesler** [comment]
> Update: they won't let me publicly list it because it's not usable by everyone: Now it is a release with the signed xpi file:
> 
> https://github.com/JackBlake-zkq/cse-plus/releases/tag/Firefox

Oh no! It makes sense, though. Thanks for getting this working!

**Comment by JackBlake-zkq** [comment]
@TetraTsunami new version FYI: https://github.com/JackBlake-zkq/cse-plus/releases/tag/v1.1.0
